version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresgl/data/
    env_file:
      - ./.env
  web:
    image: nidzhat/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value: